

all: 
	cd account; make
	cd alarm-clock; make
	cd producers-consumers; make
	cd hellothreads; make
	cd widgetmaker; make


clean:
	cd account; make clean
	cd alarm-clock; make clean
	cd producers-consumers; make clean
	cd hellothreads; make clean
	cd widgetmaker; make clean

