#!/bin/bash

Foo() {
    case "$1" in
	[0-4].*)    echo very old kernel ;&
	5.[0-2].*)  echo old kernel ;;
	5.[^0-2].*) echo new kernel ;;
	6.*)        echo newer kernel ;;
	*)          echo unknown kernel ;;
    esac
}

x=$(uname -r)
echo $x
Foo $x
