# You can add new chapters as a dependency for all.
all: chapter-5
# See how I created a new target, chapter-5; you can do the same for chapters that you work on 
chapter-5:
	cd chapter_5; make

clean:
	cd chapter_5; make clean
