#!/bin/sh
module="booga"
device="booga"
group="wheel"
mode="666"

# invoke insmod with all arguments we got
if test -f "$module.ko"
then
	/sbin/insmod  $module.ko $* || exit 1
else
	/sbin/insmod  $module.o $* || exit 1
fi

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}[0-3]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
ln -sf ${device}0 /dev/${device}
chgrp $group /dev/${device}[0-3]
chmod $mode  /dev/${device}[0-3]


