
all: dir1 dir2 dir3

dir1:	
	cd genericList; make all

dir2:
	cd phonelist; make all

dir3:
	cd template; make all

clean:
	cd genericList; make clean
	cd phonelist; make clean
	cd template; make clean
