
all:
	cd buddy-system; make
	cd mydash; make
	cd producers-consumers; make
	cd webstats; make

clean:
	cd buddy-system; make clean
	cd mydash; make clean
	cd producers-consumers; make clean
	cd webstats; make clean

