
all:
	cd doubly-linked-list; make
	#cd buddy-system; make
	cd mydash; make
	#cd producers-consumers; make
	cd webstats; make

clean:
	cd doubly-linked-list; make clean
	cd buddy-system; make clean
	cd mydash; make clean
	cd producers-consumers; make clean
	cd webstats; make clean

