
all:
	cd hello; make; echo
	cd example1; make; echo
	cd example2; make; echo
	cd proc-ex1; make; echo
	cd example3; make; echo
	cd example4; make; echo
	
clean:
	cd hello; make clean; echo
	cd example1; make clean; echo
	cd example2; make clean; echo
	cd proc-ex1; make clean; echo
	cd example3; make clean; echo
	cd example4; make clean; echo
